name: typo3-surf
type: typo3
docroot: htdocs/
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.4"
php_version: "8.1"
mysql_version: ""
use_dns_when_possible: true
mutagen_enabled: true
composer_version: "2"
additional_hostnames:
  ['deployment.typo3-surf']
web_environment:
- SURF_WORKSPACE=/var/www/html/deployment/workspace
- SURF_HOME=/var/www/html/deployment
- GIT_SSH_COMMAND=ssh -i /var/www/html/deployment/ssh/id_rsa
- TYPO3_CONTEXT=Development/Ddev
disable_settings_management: true
webimage_extra_packages: [build-essential, joe]
hooks:
  post-start:
  - exec: bash /var/www/html/.ddev/scripts/ssh-keygen.sh